server: 
    port: 9090
spring:
    cloud:
        config:
            server:
                git:
                    default-label: main
                    uri: https://github.com/AlcidesFabianFernancez/MicroserviciosJava
                    searcch-paths: config-data
    application: 
        name: config-service
